import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../../components/Navbar';
import {prisma} from '../../lib/prisma';
import Image from 'next/image';

const User: NextPage = ({name, email, image}: any) => {
  return (
    <div>
      <Head>
        <title>{name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='text-emerald-400 text-center px-12 pt-16'>
        <h1 className='text-5xl font-extrabold'>{name}</h1>
        {image && <Image src={image} width={80} height={80} className='rounded-full' />}
        <span>{email}</span>
      </div>
    </div>
  );
};

export default User;

export const getStaticProps = async ({params}: any) => {
  const data = await prisma.user.findFirst({
    where: {
      name: params.name,
    },
  });

  const user = JSON.parse(JSON.stringify(data));
  return {props: user};
};

export const getStaticPaths = async () => {
  const data = await prisma.user.findMany();
  const users = JSON.parse(JSON.stringify(data));
  const paths = users.map((user: any) => {
    return {params: {name: user.name}};
  });
  return {paths, fallback: false};
};

