import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../../components/Navbar';
import CrystalInfoPanel from '../../components/CrystalInfoPanel';
import CrystalCategoryItem from '../../components/CrystalCategoryItem';
import {prisma} from '../../lib/prisma';

const Product: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>{props.name}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='px-12 py-16'>
        <CrystalInfoPanel name={props.name} image={props.image} description={props.description} price={props.price} quantity={props.quantity} />
        <div className='text-center p-4 m-2'>
          <button className='text-lg transition ease-in-out duration-200 text-emerald-400 font-semibold hover:bg-emerald-400 hover:text-white border border-emerald-400 rounded-lg px-6 py-4'>
            Add to cart
          </button>
        </div>
        <div className='bg-white text-emerald-400 text-xl text-center font-bold pt-8 p-4'>
          <h3>You may also like:</h3>
          <CrystalCategoryItem name='Ruby' price={99} />
        </div>
      </div>
    </div>
  );
};

export default Product;

export const getStaticProps = async ({params}: any) => {
  const data = await prisma.crystal.findUnique({
    where: {
      id: parseInt(params.id),
    },
  });
  const crystal = JSON.parse(JSON.stringify(data));
  return {props: crystal};
};

export const getStaticPaths = async () => {
  const data = await prisma.crystal.findMany();
  const crystals = JSON.parse(JSON.stringify(data));
  const paths = crystals.map((crystal: any) => {
    return {params: {id: crystal.id.toString()}};
  });
  return {paths, fallback: false};
};

