import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../../components/Navbar';
import CrystalInfoPanel from '../../components/CrystalInfoPanel';
import CrystalCategoryItem from '../../components/CrystalCategoryItem';
import LoadingPage from '../../components/LoadingPage';
import {prisma} from '../../lib/prisma';

const Product: NextPage = ({data}: any) => {
  return (
    <div>
      <Head>
        <title>Crystals</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='px-12 py-16'>
        <Image src={data.image} alt={data.name} width={100} height={100} layout='responsive' />
        <CrystalInfoPanel name={data.name} description={data.description} price={data.price} quantity={data.quantity} />
        <div className='text-center p-4 m-2'>
          <button className='bg-white hover:bg-emerald-400 text-emerald-400 hover:text-white border border-emerald-400 uppercase font-semibold p-2'>
            Add to cart
          </button>
        </div>
        <div className='bg-white text-emerald-400 text-xl text-center font-bold pt-8 p-4'>
          <h3>You may also like:</h3>
          <CrystalCategoryItem name='Ruby' price={99} />
        </div>
      </div>
    </div>
  );
};

export default Product;

export const getStaticProps = async ({params}: any) => {
  let data = await prisma.crystal.findUnique({
    where: {
      id: parseInt(params.id),
    },
  });
  data = JSON.parse(JSON.stringify(data));
  return {props: data};
};

export const getStaticPaths = async () => {
  let data = await prisma.crystal.findMany();
  data = JSON.parse(JSON.stringify(data));
  const paths = data.map((crystal: any) => {
    return {params: {id: crystal.id.toString()}};
  });
  return {paths, fallback: false};
};

