import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../../components/Navbar'

const Product: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Crystals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='grid'>
        <div>
          <h2>Crystal name</h2>
        </div>
        <div>
          <p>Crystal description</p>
        </div>
        <div>
          <button className='uppercase'>Add to cart</button>
        </div>
      </div>
    </div>
  )
}

export default Product