import type { NextPage } from 'next'
import Head from 'next/head'

const Product: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Eshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>Product page</h1>
    </div>
  )
}

export default Product