import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import CartItem from '../components/CartItem';
import {useState} from 'react';
import Modal from '../components/Modal';
import {useContext} from 'react';
import {CartContext} from '../utils/CartContext';
import {Crystal} from '@prisma/client';
import Link from 'next/link';

const Cart: NextPage = () => {
  const {cartItems, setCartItems} = useContext(CartContext);
  const [modalOpen, setModalOpen] = useState(false);

  const handleCloseModal = () => {
    setModalOpen(false);
  };

  return (
    <div>
      <Head>
        <title>Cart</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Modal opened={modalOpen} handleCloseModal={handleCloseModal} />
      <div className='text-center px-10 py-16'>
        <h1 className='text-emerald-400 text-5xl font-extrabold'>Your shopping cart</h1>
      </div>
      <section className='flex flex-col items-center'>
        {cartItems.map((item: any) => (
          <CartItem
            key={item.item.id}
            id={item.item.id}
            name={item.item.name}
            image={item.item.image}
            quantity={item.quantity}
            price={item.item.price}
          />
        ))}
      </section>
      <section className='flex justify-center'>
        <div className='w-2/3 text-right text-white font-semibold text-xl rounded-lg bg-emerald-300 p-8 my-4'>
          Total price: <span className='text-2xl px-10'>{0} €</span>
        </div>
      </section>
      <div className='flex justify-center p-4'>
        <button
          onClick={() => setModalOpen(true)}
          className='text-emerald-300 bg-white text-lg font-semibold border border-emerald-300 transition ease-in-out duration-200 hover:bg-slate-50 rounded-lg p-2 m-2'
        >
          Cancel
        </button>
        <Link href='/checkout'>
          <a className='bg-emerald-300 text-white text-lg font-semibold transition ease-in-out duration-200 hover:bg-emerald-400 rounded-lg p-2 m-2'>
            Go to checkout
          </a>
        </Link>
      </div>
    </div>
  );
};

export default Cart;

