import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';

const Checkout: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Checkout</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='text-center px-10 py-16'>
        <h1 className='text-emerald-400 text-5xl font-extrabold'>Checkout</h1>
      </div>
      <div className='text-center px-10 py-16'>
        <h2 className='text-emerald-400 text-5xl font-extrabold'>Transaction details</h2>
      </div>
    </div>
  );
};

export default Checkout;

