import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import ProfileInfoPanel from '../components/ProfileInfoPanel';
import CartItemsList from '../components/CartItemsList';
import {useMutation} from '@tanstack/react-query';
import axios from 'axios';
import {useSession} from 'next-auth/react';
import useGetCurrentUser from '../utils/useGetCurrentUser';
import {Crystal} from '@prisma/client';
import {useContext} from 'react';
import {CartContext} from '../utils/CartContext';

type TransactionType = {userId: string; products: Crystal[]};

const Checkout: NextPage = () => {
  const {cartItems} = useContext(CartContext);
  const makeTransaction = useMutation((newTransaction: TransactionType) => {
    return axios.post('/api/transactions/create', newTransaction);
  });

  const handleTransaction = () => {
    //makeTransaction.mutate({userId: data.id, products: cartItems});
    //FIXME: cartItems contains quantity!
    console.log('hej');
  };

  //FIXME: should be some hook of itself
  const {data: session} = useSession();
  const isSession: boolean = session !== null && typeof session?.user?.email === 'string';
  const {data} = useGetCurrentUser(session?.user?.name, isSession);

  //TODO: loading placeholders
  return (
    <div>
      <Head>
        <title>Checkout</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='text-center px-10 py-16'>
        <h1 className='text-emerald-400 text-5xl font-extrabold'>Checkout</h1>
      </div>
      <div className='text-center px-10 py-16'>
        <h2 className='text-emerald-400 text-5xl font-extrabold'>Transaction details</h2>
      </div>
      <section>
        <div className='flex p-16'>
          <div className='basis-1/4'>
            <ProfileInfoPanel {...data} />
          </div>
          <div className='basis-3/4'>
            <CartItemsList items={cartItems} />
          </div>
        </div>
        <div className='flex justify-center'>
          <button
            onClick={handleTransaction}
            className='bg-emerald-300 text-white hover:bg-emerald-400 transition ease-in-out duration-300 font-bold text-lg rounded-lg p-3'
          >
            Make Transaction
          </button>
        </div>
      </section>
    </div>
  );
};

export default Checkout;

