import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import ProfileInfoPanel from '../components/ProfileInfoPanel';
import CartItemsList from '../components/CartItemsList';
import {useMutation} from '@tanstack/react-query';
import axios from 'axios';
import {useSession} from 'next-auth/react';
import useGetCurrentUser from '../utils/useGetCurrentUser';

const Checkout: NextPage = () => {
  const makeTransaction = useMutation(newTransaction => {
    //TODO: make the endpoint
    return axios.post('/', newTransaction);
  });

  //FIXME: should be some hook of itself
  const {data: session} = useSession();
  const isSession: boolean = session !== null && typeof session?.user?.email === 'string';
  const {data} = useGetCurrentUser(session?.user?.email, isSession);

  //TODO: loading placeholders
  return (
    <div>
      <Head>
        <title>Checkout</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='text-center px-10 py-16'>
        <h1 className='text-emerald-400 text-5xl font-extrabold'>Checkout</h1>
      </div>
      <div className='text-center px-10 py-16'>
        <h2 className='text-emerald-400 text-5xl font-extrabold'>Transaction details</h2>
      </div>
      <section>
        <div className='flex p-16'>
          <div className='basis-1/4'>
            <ProfileInfoPanel {...data} />
          </div>
          <div className='basis-3/4'>
            <CartItemsList />
          </div>
        </div>
        <div className='flex justify-center'>
          <button className='bg-emerald-300 text-white hover:bg-emerald-400 transition ease-in-out duration-300 font-bold text-lg rounded-lg p-3'>
            Make Transaction
          </button>
        </div>
      </section>
    </div>
  );
};

export default Checkout;

