import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import CrystalListItem from '../components/CrystalListItem';
import LoadingPage from '../components/LoadingPage';
import {Crystal} from '@prisma/client';
import {prisma} from '../lib/prisma';

const Crystals: NextPage = ({crystals}: any) => {
  return (
    <div>
      <Head>
        <title>Crystals</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='text-emerald-400 text-center px-12 pt-16'>
        <h1 className='text-5xl font-extrabold'>Crystals List</h1>
      </div>
      <div className='grid grid-cols-4 justify-around gap-8 p-12 my-8'>
        {crystals.map((crystal: Crystal) => (
          <CrystalListItem key={crystal.id} id={crystal.id} name={crystal.name} image={crystal.image} />
        ))}
      </div>
      <div className='text-emerald-400 text-center p-10'>
        <h2 className='text-4xl font-bold text-center'>Categories</h2>
      </div>
    </div>
  );
};

export default Crystals;

export const getStaticProps = async () => {
  const data = await prisma.crystal.findMany();
  const crystals = JSON.parse(JSON.stringify(data));
  return {props: {crystals}};
};

