import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import CrystalListItem from '../components/CrystalListItem'
import useGetAllCrystals from '../utils/useGetAllCrystals'
import useGetAllCategories from '../utils/useGetAllCategories'
import LoadingPage from '../components/LoadingPage'
import ProgressBar from '../components/ProgressBar'
import { Crystal} from '@prisma/client'


const Crystals: NextPage = () => {
  const crystals = useGetAllCrystals()
  const categories = useGetAllCategories()

  if (crystals.isLoading || categories.isLoading) {
    return (
      <>
        <Navbar />
        <ProgressBar progress={4}/>
        <LoadingPage />
      </>
    )
  }

  if (crystals.isError || categories.isError) {
    return <div>Error...</div>
  }


  const crystalItems = crystals.data.map((c: Crystal) => <CrystalListItem key={c.id} id={c.id} name={c.name} image={c.image}/>)
  //TODO: map categories and make a component for it

  return (
    <div>
      <Head>
        <title>Crystals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='text-emerald-400 text-center px-8 pt-12'>
        <h1 className='text-4xl font-bold'>Crystals List</h1>
      </div>
      <div className='flex flex-col lg:flex-row justify-around p-12'>
        {crystalItems}
      </div>
      <div className='text-emerald-400 text-center p-10'>
        <h2 className='text-4xl font-bold text-center'>Categories</h2>
      </div>
    </div>
  )
}

export default Crystals
