import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import CrystalListItem from '../components/CrystalListItem'
import useGetCrystals from '../utils/useGetCrystals'
import { Crystal } from '@prisma/client'


const Crystals: NextPage = () => {
  const crystals = useGetCrystals()
  if (crystals.isLoading) {
    return <div>Loading...</div>
  }


  const crystalItems = crystals.data.map((c: Crystal) => <CrystalListItem key={c.id} id={c.id} name={c.name}/>)

  return (
    <div>
      <Head>
        <title>Crystals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar />
    <div className='text-emerald-400 text-center px-8 pt-12'>
      <h2 className='text-4xl font-bold'>Crystals List</h2>
    </div>
    <div className='flex justify-around p-12'>
      {crystalItems}
    </div>
    </div>
  )
}

export default Crystals
