import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';

const Inventory: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Inventory</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='p-20'>
        <h1 className='text-emerald-400 text-5xl font-extrabold text-center'>My Inventory</h1>
      </div>
      <section></section>
    </div>
  );
};

export default Inventory;

