import type {NextPage} from 'next';
import Head from 'next/head';
import {useForm} from 'react-hook-form';
import Navbar from '../components/Navbar';

interface LoginFormProps {
  username: string;
  password: string;
}

const Login: NextPage = () => {
  const {
    register,
    handleSubmit,
    formState: {errors},
  } = useForm<LoginFormProps>();

  const loginSubmit = (data: LoginFormProps) => {
    console.log(data);
  };

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='flex flex-col items-center text-center bg-emerald-400 rounded-lg p-16 m-8'>
        <form onSubmit={handleSubmit(loginSubmit)}>
          <input {...register('username', {required: true})} type='text' name='username' placeholder='Username' className='rounded-2xl p-2 my-2' />
          <input
            {...register('password', {required: true})}
            type='password'
            name='password'
            placeholder='Password'
            className='rounded-2xl p-2 my-2'
          />
          <button className='text-white bg-emerald-300 cursor-pointer font-bold text-sm rounded-lg px-8 py-2 mt-8'>Login</button>
        </form>
      </div>
    </div>
  );
};

export default Login;

