import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import OrderItem from '../components/OrderItem';
import useGetUserOrders from '../utils/useGetUserOrders';
import LoadingPage from '../components/LoadingPage';
import {Order} from '@prisma/client';

const Orders: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Orders</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
    </div>
  );
};

export default Orders;

