import type {NextPage} from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';

const Orders: NextPage = () => {
  return (
    <div>
      <Head>
        <title>My Profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
    </div>
  );
};

export default Orders;

