import type {NextPage} from 'next';
import Head from 'next/head';
import {useForm} from 'react-hook-form';
import {useMutation} from '@tanstack/react-query';
import axios from 'axios';
import Navbar from '../components/Navbar';

interface SigninFormProps {
  username: string;
  email: string;
  password: string;
}

const Signup: NextPage = () => {
  const createUser = useMutation((newUser: SigninFormProps) => {
    return axios.post('/api/signin', newUser);
  });

  const {
    register,
    handleSubmit,
    formState: {errors},
  } = useForm<SigninFormProps>();

  const signinSubmit = (data: SigninFormProps) => {
    createUser.mutate(data);
  };

  return (
    <div>
      <Head>
        <title>Sign up</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <div className='text-center bg-emerald-400 rounded-lg p-16 m-8'>
        <form onSubmit={handleSubmit(signinSubmit)} className='flex flex-col items-center'>
          <input
            {...register('username', {required: true, maxLength: 20})}
            type='text'
            name='username'
            placeholder='Username'
            className='rounded-2xl p-2 my-2'
          />
          <input {...register('email', {required: true})} type='email' name='email' placeholder='Password' className='rounded-2xl p-2 my-2' />
          <button className='text-white bg-emerald-300 cursor-pointer font-bold text-sm rounded-lg px-8 py-2 mt-8'>Sign up</button>
        </form>
      </div>
    </div>
  );
};

export default Signup;

