import type { NextPage } from 'next'
import Head from 'next/head'

const Signin: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Signin page</h1>
    </div>
  )
}

export default Signin
