import type { NextPage } from 'next'
import Head from 'next/head'
import { useForm } from 'react-hook-form'
import { useMutation } from '@tanstack/react-query'
import axios from 'axios'



interface SigninFormProps {
  username: string,
  email: string,
  password: string
}

const Signin: NextPage = () => {

  const createUser = useMutation((newUser: SigninFormProps) => {
    return axios.post('/api/signin', newUser)
  })

  const { register, handleSubmit, formState: { errors }} = useForm<SigninFormProps>()

  const signinSubmit = (data: SigninFormProps) => {
    createUser.mutate(data)
  }

  return (
    <div>
      <Head>
        <title>Signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col items-center p-12'>
        <div className='text-center p-6'>
          <h1 className='text-emerald-400 text-5xl font-bold'>Signin</h1>
        </div>
        <div className='bg-emerald-400 text-center caret-emerald-400 p-8'>
          <form onSubmit={handleSubmit(signinSubmit)}>
            <div className='p-2'>
              <label htmlFor="username" className='text-white'>Username</label>
              <input {...register('username')} type="text" name='username'/>
            </div>
            <div className='p-2'>
              <label htmlFor="email" className='text-white'>Email</label>
              <input {...register('email')} type="email" name='email'/>
            </div>
            <button className='bg-white text-emerald-400 cursor-pointer uppercase text-sm font-semibold px-3 py-2 m-3'>Signin</button>
          </form>
        </div> 
      </div>
    </div>
  )
}

export default Signin
